# Generated by Django 2.2 on 2020-09-05 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='ext_id',
        ),
    ]
