# Generated by Django 2.2 on 2020-09-05 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200905_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pincode',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(6)]),
        ),
    ]
