# Generated by Django 2.2 on 2020-09-06 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
                ('body', models.TextField(blank=True, max_length=300, unique=True)),
                ('summary', models.CharField(max_length=30, unique=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='doc/')),
                ('category', models.ManyToManyField(to='content.Category')),
            ],
        ),
    ]
